package com.rainbowpunch.jetedge.core.limiters.special;

import com.rainbowpunch.jetedge.core.limiters.Limiter;

import java.util.Random;
import java.util.function.Function;
import java.util.function.Supplier;

/**
 * There are times when its easier to create data in one way, and then use a conversion function to create the type you're actually needing.
 *      A primary example of this is accessing Enum fields.  It is easier to use an Enum Limiter to create an enum object and then access
 *      that enum's methods via a function.
 * @param <T> The type of the provided Limiter's output
 * @param <U> The type of the output of the provided function which takes in type T
 */
public class MorphLimiter<T, U> implements Limiter<U> {

    private Limiter<T> dataCreator;
    private Function<T, U> morphingFunction;

    /**
     * This method will take a current limiter and morph its value based on a provided Function that takes the output of the limiter.
     * @param dataCreator the limiter for T
     * @param morphingFunction a function that takes in an object of T and returns an objec of U after altering it.
     */
    public MorphLimiter(Limiter<T> dataCreator, Function<T, U> morphingFunction) {
        this.dataCreator = dataCreator;
        this.morphingFunction = morphingFunction;
    }

    /**
     * A common morph is getting the string output of a generated object.  This outputs the .toString() method of whatever objects
     *      are generated by the provided limiter.
     * @param dataCreator the limiter for X
     * @return
     */
    public static <X> MorphLimiter castToString(Limiter<X> dataCreator) {
        return new MorphLimiter<X, String>(dataCreator, (data) -> data.toString());
    }

    @Override
    public Supplier<U> generateSupplier(Random random) {
        return () -> {
            T data = dataCreator.generateSupplier(random).get();
            return morphingFunction.apply(data);
        };
    }

}
